# Generated by Django 3.2.9 on 2021-12-03 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='busroutes',
            name='geoLocLat',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='busroutes',
            name='geoLocLon',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='busroutes',
            name='roads',
            field=models.TextField(default=0.0),
            preserve_default=False,
        ),
    ]
